server:
  port: 8003

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.lc.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml

spring:
  application:
    name: microservicecloud-dept #对外暴露的微服务名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud03?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    dbcp2:
      min-idle: 10
      initial-size: 10
      max-total: 10
      max-wait-millis: 200

eureka:
  client:
    service-url:
      #单机defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: microservicecloud-dept8003 #设置为服务实例名 改进
    prefer-ip-address: true #设置显示服务器ip 改进

info:
  app.name: lc-microservicecloud
  company.name: lc.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}